// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ListMessages() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"h-[65vh] overflow-y-auto p-4 border-b border-gray-700\" x-ref=\"messagesContainer\"><template x-for=\"message in messages\" :key=\"message.id\"><div x-show=\"message.message?.trim() || message.gif_url\" class=\"mb-4 p-3 bg-gray-700 rounded-lg\"><div class=\"flex justify-between items-start mb-2\"><span class=\"font-semibold text-gray-400\" x-text=\"message.username\"></span> <span class=\"text-xs text-gray-500\" x-text=\"formatTime(message.created_at)\"></span></div><p x-show=\"message.message?.trim()\" class=\"text-gray-100 mb-2\" x-text=\"message.message\"></p><div x-show=\"message.gif_url\" class=\"mt-2\"><div class=\"relative inline-block group rounded-md overflow-hidden\"><img :src=\"message.gif_url\" :alt=\"message.message || 'GIF'\" class=\"max-w-xs max-h-48 object-contain block transition-transform duration-200 ease-in-out group-hover:scale-[1.02]\" loading=\"lazy\"><div class=\"absolute inset-0 bg-black/0 group-hover:bg-black/10 transition-colors\"></div><div class=\"absolute bottom-2 left-2 pointer-events-none opacity-0 group-hover:opacity-100 transition-opacity\"><span class=\"bg-black/60 text-white text-xs font-bold px-2 py-0.5 rounded\">GIF</span></div></div></div></div></template><div x-show=\"messages.length === 0\" class=\"text-center text-gray-400 py-8\">no messages... nothing to whisp</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
