# VM 2 is the production worker in this cluster.
nodeSelector:
    kubernetes.io/hostname: homelab-vm2

whisp:
    configSecret: whisp-config

resources:
    whisp:
        requests:
            cpu: 50m
            memory: 128Mi
        limits:
            cpu: 500m
            memory: 512Mi

ingress:
    enabled: true
    className: traefik
    annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web
    hosts:
        - whisp.andrearcaina.ca
        - www.whispapp.dev
        - whispapp.dev
    path: /
